# Generated by Django 3.0.4 on 2020-03-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('address', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.District')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingGadgetInstance',
            fields=[
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.TextField()),
                ('readings', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.House')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
