# Generated by Django 3.0.4 on 2020-03-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinggadgetinstance',
            name='model',
        ),
        migrations.AddField(
            model_name='trackinggadgetinstance',
            name='type',
            field=models.CharField(choices=[('power', 'Электрический'), ('water', 'Водный'), ('gas', 'Газовый')], default=None, max_length=13, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.House', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='manufacturer',
            field=models.CharField(max_length=20, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='readings',
            field=models.CharField(max_length=15, verbose_name='Показания'),
        ),
    ]
