# Generated by Django 3.0.4 on 2020-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200331_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='readings',
            field=models.IntegerField(verbose_name='Показания'),
        ),
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='type',
            field=models.CharField(choices=[('электричество', 'Электрический'), ('вода', 'Водный'), ('газ', 'Газовый')], default=None, max_length=13, verbose_name='Тип'),
        ),
    ]
