# Generated by Django 3.0.4 on 2020-04-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200331_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinggadgetinstance',
            name='type',
            field=models.CharField(choices=[('электрический', 'Электрический'), ('водный', 'Водный'), ('газовый', 'Газовый')], default=None, max_length=13, verbose_name='Тип'),
        ),
    ]
