# Generated by Django 3.0.4 on 2020-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200404_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_m', models.IntegerField()),
                ('name', models.TextField()),
                ('state', models.IntegerField()),
                ('dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'modems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_id', models.TextField()),
                ('parent', models.TextField()),
                ('text', models.TextField()),
                ('type', models.IntegerField()),
                ('sn_c', models.IntegerField()),
                ('sn_m', models.TextField()),
            ],
            options={
                'db_table': 'tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValuesT1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField()),
                ('time_stamp_db', models.DateTimeField()),
                ('sn_m', models.IntegerField()),
                ('sn_c', models.IntegerField()),
                ('type', models.IntegerField()),
                ('error', models.TextField()),
                ('addr', models.IntegerField()),
                ('power', models.FloatField()),
                ('power_q', models.FloatField(db_column='power_Q')),
                ('power_s', models.FloatField(db_column='power_S')),
                ('energy', models.FloatField()),
                ('energy_a', models.FloatField(db_column='energy_A')),
                ('energy_r', models.FloatField(db_column='energy_R')),
                ('u', models.FloatField()),
                ('i', models.FloatField()),
                ('freq', models.FloatField()),
                ('cos', models.FloatField()),
                ('time_stamp', models.TextField()),
            ],
            options={
                'db_table': 'values_t1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TrackingGadgetInstance',
        ),
    ]
