# Generated by Django 3.0.4 on 2020-04-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200428_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modems',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.DeleteModel(
            name='ValuesT1',
        ),
    ]
