# Generated by Django 3.0.4 on 2020-04-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_modems_tree_types_valuest1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuest1',
            old_name='energy_a',
            new_name='energy_A',
        ),
        migrations.RenameField(
            model_name='valuest1',
            old_name='energy_r',
            new_name='energy_R',
        ),
        migrations.RenameField(
            model_name='valuest1',
            old_name='power_q',
            new_name='power_Q',
        ),
        migrations.RenameField(
            model_name='valuest1',
            old_name='power_s',
            new_name='power_S',
        ),
    ]
