# Generated by Django 3.0.4 on 2020-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='Тема вопроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание вопроса')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ на вопрос')),
            ],
        ),
    ]
